### ISSUE TITLE
Errors while building the app via solution

### ISSUE THREAD

**Issue by pronoy2108** [FireCubeStudios/Protecc#1]
Severity	Code	Description	Project	File	Line	Suppression State
Error	WMC1006	Cannot resolve Assembly or Windows Metadata file 'E:\guzel\CubeKit.UI\bin\x86\Debug\CubeKit.UI.dll'	E:\guzel\TemplateApp\Protecc.csproj	E:\guzel\TemplateApp\Protecc.csproj	1	
Error	WMC1006	Cannot resolve Assembly or Windows Metadata file 'Type universe cannot resolve assembly: System.Runtime, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a.'	E:\guzel\TemplateApp\Protecc.csproj	E:\guzel\TemplateApp\Protecc.csproj	1	
Error	WMC1006	Cannot resolve Assembly or Windows Metadata file 'Type universe cannot resolve assembly: System.Runtime, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a.'	E:\guzel\CubeKit.UI\CubeKit.UI.csproj	E:\guzel\CubeKit.UI\CubeKit.UI.csproj	1	
Error	CS2001	Source file 'E:\guzel\CubeKit.UI\obj\x86\Debug\Controls\Settings\SettingsBlockControl.g.i.cs' could not be found.	E:\guzel\CubeKit.UI\CubeKit.UI.csproj	E:\guzel\CubeKit.UI\CSC	1	
Error	CS2001	Source file 'E:\guzel\CubeKit.UI\obj\x86\Debug\Controls\Settings\SettingsDisplayControl.g.i.cs' could not be found.	E:\guzel\CubeKit.UI\CubeKit.UI.csproj	E:\guzel\CubeKit.UI\CSC	1	
Error	CS2001	Source file 'E:\guzel\TemplateApp\obj\x86\Debug\AddAccountPage.g.i.cs' could not be found.	E:\guzel\TemplateApp\Protecc.csproj	E:\guzel\TemplateApp\CSC	1	
Error	CS2001	Source file 'E:\guzel\TemplateApp\obj\x86\Debug\App.g.i.cs' could not be found.	E:\guzel\TemplateApp\Protecc.csproj	E:\guzel\TemplateApp\CSC	1

**Comment by FireCubeStudios** [comment]
try cleaning and rebuilding the solution

**Comment by FireCubeStudios** [comment]
cleaning and rebuilding should work as confirmed by a user on reddit
