### ISSUE TITLE
Windows Hello not working with Pin

### ISSUE THREAD

**Issue by FireCubeStudios** [FireCubeStudios/Protecc#10]
Some users are reporting Windows Hello not working with Pin.

**Comment by FireCubeStudios** [comment]
so while debugging i found another bug lol

**Comment by jh30uk** [comment]
Correct pin does not in Protecc work but is correct and works in Windows, cannot try Hello/Fingerprint as latest Win 11 DEV has removed NetFrame 3.5 for now.

**Comment by DaiichiKuronama** [comment]
I'm the person from Reddit. My Windows version is Windows 11 Pro 21H2 Build 22000.858
I only have PIN available in Windows Hello Sign-in options because I keep my webcam turned off if I don't need it and I don't have a fingerprint scanner. I did also confirm with another 3rd-party UWP app that the problem is not on my end. I hope that helps.

**Comment by FireCubeStudios** [comment]
> I'm the person from Reddit. My Windows version is Windows 11 Pro 21H2 Build 22000.858 I only have PIN available in Windows Hello Sign-in options because I keep my webcam turned off if I don't need it and I don't have a fingerprint scanner. I did also confirm with another 3rd-party UWP app that the problem is not on my end. I hope that helps.

Hi can you send a screenshot of what the screen looks like when the Windows Hello login failed, There should be a text like "Authentication not supported" which will give me information on what part fails

**Comment by FireCubeStudios** [comment]
Ok both bugs have been fixed and the changes are uploaded to GitHub. A store fix should be out later today.

**Comment by jh30uk** [comment]
All working now with Hello/Pin, you would need someone not latest on Win11 Dev to test Hello/Fingerprint as for now as I said previouslyNetFrame 3.5 is not working in this build.

**Comment by DaiichiKuronama** [comment]
Working with Hello/ PIN. New issue: after closing, reopening duplicates all auths I've created, so i have two of everything. Deleting one deletes them both upon reopening.

**Comment by FireCubeStudios** [comment]
> Working with Hello/ PIN. New issue: after closing, reopening duplicates all auths I've created, so i have two of everything. Deleting one deletes them both upon reopening.

Please make a new issue for this

**Comment by jh30uk** [comment]
New Win 11 Dev today and NetFrame 3.5 is fixed so i can now confirm your App works with Hello/Fingerprint as well as the PIn.
