### ISSUE TITLE
White pixel visible when choosing to hide code for account starting with 'T'.

### ISSUE THREAD

**Issue by Octaviorios** [FireCubeStudios/Protecc#12]
Title is pretty self explanatory. I know it's not that important, but it does trigger me to unknown horizons hehe.

You can see it at the top left here>
![image](https://user-images.githubusercontent.com/12775041/187493209-defd91fd-6a79-4b73-96bf-b32599cfc2f9.png)

Not sure what other capital letters could trigger the same effect, might be worth checking that out.

**Comment by FireCubeStudios** [comment]
Thanks I cant unsee it.

**Comment by FireCubeStudios** [comment]
fixed with latest gh and store fix coming soon
