### ISSUE TITLE
[QOL Suggestion] Make it so clicking on the code will copy to clipboard.

### ISSUE THREAD

**Issue by Octaviorios** [FireCubeStudios/Protecc#13]
Right now, clicking on a code does nothing, i'd suggest making it so it would copy the code to clipboard.

I know there's already a little button for that, but at least personally i would much rather click the big code box when quickly trying to copy the code to a website. It also feels intuitive (personal opinion).

**Comment by FireCubeStudios** [comment]
I explained in the reddit reply (https://www.reddit.com/r/Windows11/comments/x0zkcy/comment/imeykl1/?utm_source=share&utm_medium=web2x&context=3) why I didn't add this. Personally I will not add it but if someone does a pr I will accept it. Closing this issue for now
