### ISSUE TITLE
duplicate entries after reopening with Hello enabled.

### ISSUE THREAD

**Issue by DaiichiKuronama** [FireCubeStudios/Protecc#14]
Working with Hello/ PIN. New issue: after closing, reopening duplicates all auths I've created, so I have two of everything. Deleting one deletes them both upon reopening.

**Comment by FireCubeStudios** [comment]
I see this happens after the OOBE is launched. Easy fix I will submit

**Comment by Yohan-Janolin** [comment]
And if you click on 'Add' and then cancel, the duplicated entries disappear until next launch

**Comment by FireCubeStudios** [comment]
I can't reproduce this bug although I believe it is due to the faulty usage of credential service. I will try to use Iservice and ioc stuff in next release according to advice from big brain dev on uwp discord

**Comment by FireCubeStudios** [comment]
fixed in latest github and will come to store
