### ISSUE TITLE
MIT vs UNLICENSE

### ISSUE THREAD

**Issue by FireCubeStudios** [FireCubeStudios/Protecc#19]
Discussion on whether to use UNLICENSE or MIT. I am thinking about switching to MIT based on what I heard in r/dotnet. What do you guys think about this idea? If there are no objections I will switch

**Comment by ZEROPOINTBRUH** [comment]
keep your current license

**Comment by CePur** [comment]
Make it anything but UNLICENSE. Asap.  MIT is fine.

**Comment by FireCubeStudios** [comment]
Switched to MIT
