### ISSUE TITLE
I'm unable to build this under VS 22 on Windows 11

### ISSUE THREAD

**Issue by ezxpro** [FireCubeStudios/Protecc#23]
This is what I get instead:
![image](https://user-images.githubusercontent.com/15344931/188276047-d266b151-0963-45a8-bb6e-97d3388bbe7a.png)

**Comment by spooksbit** [comment]
Double check to see if you have nuget package source enabled. Your error messages seem to suggest that you don't have it enabled (or you can't reach it?).

In VS, right click the solution -> "Manage Nuget Packages for Solution", and then click the gear to see what package source you have enabled. You can see that "Microsoft Visual Studio Offline Packages" (referenced in your error logs) should be referencing what you have on your local hard drive vs actually fetching the nuget packages from nuget.org.

![image](https://user-images.githubusercontent.com/71300703/188277259-bb7001d5-9f8c-4948-83c0-5067100d1d3e.png)

![image](https://user-images.githubusercontent.com/71300703/188277242-b9e70bb0-2d0a-457d-aa4a-fd6d240e9d37.png)

**Comment by FireCubeStudios** [comment]
Yeah looks like the nuget packages are missing. Do what @spooksbit suggested and also check the correct nuget packages are installed

**Comment by ezxpro** [comment]
@spooksbit @FireCubeStudios Yeah, that was the problem. Now there's apparently a single error preventing me from building it.
It's complaining about a missing certificate:
`
Error		No certificate found with the supplied thumbprint: 00E95C3FAD42BD7746B10B1BEFB33D44991CE752	
`

**Comment by ezxpro** [comment]
@FireCubeStudios that solved the dependency problem. Now I'm getting a `NullReferenceException` at light 66 of `OOBEPage.xaml.cs`
Apparently it's an attempt to modify a property of  an object that was not instantiated.  I'm just trying to build this for fun, so I don't really know how to fix this.

**Comment by FireCubeStudios** [comment]
when vs hits the exception it will show a flyout and in that flyout you can check a box that ignores that exception

Lol i need to use #nullable next time for this
