### ISSUE TITLE
Build Issue - Package Certificate not found

### ISSUE THREAD

**Issue by spooksbit** [FireCubeStudios/Protecc#24]
I haven't used UWP before, but I got this error when trying to build the solution after cloning:

`No certificate found with the supplied thumbprint: 00E95C3FAD42BD7746B10B1BEFB33D44991CE752`		

I'm assuming it's referencing your own private key. Since the key isn't distributed in the repo (good thing), I had to go ahead and generate my own package key and include it in the manifest just to build the solution.

1. Right click the project in VS -> Properties
2. "Application" tab -> "Package Manifest..." -> "Choose Certificate..."
3. Click "Create..." on the dialog to create a new certificate.

This just wasn't clear to me initially, and the only suggestion I could make is include it in the README? Is there a more correct way to build the solution or is a package key simply required?

**Comment by FireCubeStudios** [comment]
Added a note in readme ✔️
I don't think a package key is required but I am not sure however creating a new certificate which you did does work.
