### ISSUE TITLE
Adding more than 20 2FA accounts creates lots of issues.

### ISSUE THREAD

**Issue by Kafman** [FireCubeStudios/Protecc#29]
Hi,

If you add more than 20 different 2FA accounts, the apps behaves completely erratic.

For instance:

1. It won't led you add a 21st account or more.
2. Performance issues, memory leaks: ![image](https://user-images.githubusercontent.com/78336297/188308042-90556338-0373-4371-abac-e4e93fb06a10.png)
3. Closing and reopening the app with 20 accounts, will duplicate your existing 2FA accounts: ![image](https://user-images.githubusercontent.com/78336297/188308206-97e4c91c-e57f-422d-af8c-32ac8f496c87.png) (Probably related to #14)
4.  Windows Hello sometimes will take a lof of time to ask for credentials.

**Comment by FireCubeStudios** [comment]
1. Yes thats because credential locker only supports upto 20 entries.
2. What actions cause the memory leaks? Is it just having more than 20 accounts? Does it reduce if there is less than 20 accounts?
3. This is being looked at
4. How often does it take a long time to ask for credentials?

**Comment by Kafman** [comment]
> 1. Yes thats because credential locker only supports upto 20 entries.
> 2. What actions cause the memory leaks? Is it just having more than 20 accounts? Does it reduce if there is less than 20 accounts?
> 3. This is being looked at
> 4. How often does it take a long time to ask for credentials?

1. Would there be a possibility to support more than 20?
2. It is having the 20 accounts at the same time, as soon as I launch the app, I can see in Task Manager a CPU spike and memory usage increasing. I have removed 5 accounts and I can see that the memory usage is well and stable.
3. Gotcha.
4. With the 20 accounts, on first launch is almost instantly, if I closed it and launch it a second time, it can take between 15-20 seconds to show the Windows Hello window.

**Comment by FireCubeStudios** [comment]
> > 1. Yes thats because credential locker only supports upto 20 entries.
> 
> > 2. What actions cause the memory leaks? Is it just having more than 20 accounts? Does it reduce if there is less than 20 accounts?
> 
> > 3. This is being looked at
> 
> > 4. How often does it take a long time to ask for credentials?
> 
> 
> 
> 1. ~~Would there be a possibility to support more than 20?~~ Edit: I see that's a limitation from MS... goddamn, I love this app but I need something that supports more than 20 accounts...
> 
> 2. It is having the 20 accounts at the same time, as soon as I launch the app, I can see in Task Manager a CPU spike and memory usage increasing. I have removed 5 accounts and I can see that the memory usage is well and stable.
> 
> 3. Gotcha.
> 
> 4. With the 20 accounts, on first launch is almost instantly, if I closed it and launch it a second time, it can take between 15-20 seconds to show the Windows Hello window.


Hi for the 20 account limitation there is another version of Protecc that uses encrypted database instead of credential locker and will support 20+ accounts, syncing, groups and images due to no limitations however that one will probably be paid
2. I see I believe it's because the animated text box control is heavy to use and isn't designed to have 20 instances. I will think about what I can do with this
4. The reason the first launch is fast is because of the pre launch technique. I will add optimisation to make initial windows hello launch faster

**Comment by FireCubeStudios** [comment]
Alright so I have added it so that if there are more than 10 cards the subsequent cards wont have animation. Yes it is not ideal but it improves performance

**Comment by FireCubeStudios** [comment]
And I added a block to add more than 20 accounts + startup improvements. I think this should resolv the issues so I am closing this now
