### ISSUE TITLE
Bugs in exporting keys

### ISSUE THREAD

**Issue by Goojoe** [FireCubeStudios/Protecc#31]
It's a great application, but it has some problems right now.
1. Can't move account sorting
1. Can't edit account after creation
1. Exporting wrong Keys (Exprot keys as yaml), both are `8CE7ED3060`.
1. Account disappears after exporting Keys and needs to be restarted to be visible
1. Parse and import `otpauth://totp`
1. Multi-language support (Chinese)

Hope you can solve these problems, thanks!

**Comment by FireCubeStudios** [comment]
1. #27 
2. #16 
3. Looks like the key is not being exported, only the resource strange
4. Good find I didn't notice this bug
5. #4 
6. Create a new issue for localization so it can be tracked please

I will rename this issue for the export bugs but thanks for all the suggestions.

**Comment by FireCubeStudios** [comment]
Fixed in the PR by spooksbit
