### ISSUE TITLE
Does not work for me period

### ISSUE THREAD

**Issue by jh30uk** [FireCubeStudios/Protecc#36]
I have no clue what is wrong.

As a test I export only one account as I know it cannot import more than one at a time so in Google Authenticator, I choose Amazon.

I then ask it to Scan Code and eventually it does read it after a long delay and me messing with zoom, and the info is filled in asking for "My Name" < I assume this means Amazon, but the Code appears to be too long (I have tried to add it manually also).

**Comment by FireCubeStudios** [comment]
This is because issue key uri is not supported yet (a custom format google uses). Support will be added and is tracked in issue #4
