### ISSUE TITLE
Use proper API for screen capture disablement

### ISSUE THREAD

**Issue by Fei1Yang** [FireCubeStudios/Protecc#37]
The current implementation for "Blur codes" only blurs them when unfocused, other programs can still take a screenshot and get the code if the program is on foreground.

However Microsoft has provided [ApplicationView.IsScreenCaptureEnabled](https://learn.microsoft.com/en-us/uwp/api/windows.ui.viewmanagement.applicationview.isscreencaptureenabled?view=winrt-22621#windows-ui-viewmanagement-applicationview-isscreencaptureenabled) property for screen capture disabling.

Switching to this property would not only disable screen capture even when the app is on foreground, but also simplify the codebase since background detection is no longer required.

Here is the sample code: [windows-universal-samples/Samples/DisablingScreenCapture](https://github.com/microsoft/windows-universal-samples/tree/main/Samples/DisablingScreenCapture)

**Comment by FireCubeStudios** [comment]
Wow I never knew about this Api thanks for posting it

**Comment by FireCubeStudios** [comment]
Added in github version. It will come to store in next update
