### ISSUE TITLE
Optimize readme.md

### ISSUE THREAD

**Issue by FireCubeStudios** [FireCubeStudios/Protecc#38]
currently it is ugly. we must make it look hot, images, badges, links, contributor list and anything else!

**Comment by Mannuel25** [comment]
Hello @FireCubeStudios , I'd love to take this up for hacktoberfest. Kindly assign it to me. Thanks

**Comment by FireCubeStudios** [comment]
Done!

**Comment by Mannuel25** [comment]
> Done!

 Thank you
