### ISSUE TITLE
Adding Contributing.md with proper instructions to contribute to the project

### ISSUE THREAD

**Issue by Mitternachtsmond** [FireCubeStudios/Protecc#46]
- The file will make the job of new contributors easier since they can follow the instructions in much better way

**Comment by FireCubeStudios** [comment]
Sounds good. What are the specific details that should be included in a contributing.md?

**Comment by Mitternachtsmond** [comment]
- First would be steps to fork the project
- Then create a branch
- Add upstream
- Work on the issue
- Push it to local
- Create a PR
- Add the details of your changes
- End would contain links to useful git resources for beginners
- Each of the above steps would contain the code associated with it in case someone does not want to read through the docs of git

**Comment by Mitternachtsmond** [comment]
@FireCubeStudios 
Please review PR #53

**Comment by FireCubeStudios** [comment]
Closing as PR #53 is adding this
