### ISSUE TITLE
Updating the look of README 

### ISSUE THREAD

**Issue by PeritusDeveloper** [FireCubeStudios/Protecc#47]
## Proposed Changes

- The license area needs to be written to align things at right place
- The copyright position can be such that it is centered aligned and at the end of README
- License file should be LICENSE.md and not LICENSE.txt
- Add link to the discussion session in the readme section

**Comment by FireCubeStudios** [comment]
Added labels, if anyone is interested to be assigned then just ask

**Comment by PeritusDeveloper** [comment]
I want to do it
assign it to me please @FireCubeStudios

**Comment by FireCubeStudios** [comment]
I have assigned but there is a pr #48 that also has improvements for the pr. wait until it is merged then work on your improvements

**Comment by PeritusDeveloper** [comment]
Sure I will wait

**Comment by FireCubeStudios** [comment]
Alright that pr was merged so you can add this

**Comment by PeritusDeveloper** [comment]
On it
