### ISSUE TITLE
Adding CODE_OF_CONDUCT.md

### ISSUE THREAD

**Issue by kailashchoudhary11** [FireCubeStudios/Protecc#49]
code_of_conduct is an important part of documentation and it should be included in this repo as well!

**Comment by FireCubeStudios** [comment]
What is included in a code of conduct?

**Comment by kailashchoudhary11** [comment]
A code of conduct defines standards for how to engage in a community. It signals an inclusive environment that respects all contributions. It also outlines procedures for addressing problems between members of your project's community. More [here](https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/adding-a-code-of-conduct-to-your-project)

**Comment by FireCubeStudios** [comment]
Ok I have assigned labels. anyone who is interested to make this document can do it

**Comment by kailashchoudhary11** [comment]
I'm interested can you assign it to me?

**Comment by FireCubeStudios** [comment]
Done

**Comment by kailashchoudhary11** [comment]
I have made a PR as well. Please review!

**Comment by FireCubeStudios** [comment]
closing issue since pr accepted

**Comment by kailashchoudhary11** [comment]
Thank You!
